import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { DefaultSeo, NextSeo } from "next-seo";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <DefaultSeo
        title="MurrayGPT: Generate Bill Murray quotes."
        description="Bill Murray quotes generated by AI."
        canonical="https://murraygpt.vercel.app"
        openGraph={{
          url: "https://murraygpt.vercel.app",
          title: "MurrayGPT: Generate Bill Murray quotes.",
          description: "Bill Murray quotes generated by AI.",
          images: [
            {
              url: "https://murraygpt.vercel.app/images/billmurray/ghostbusters.webp",
              width: 800,
              height: 600,
              alt: "Bill Murray in Ghostbusters",
              type: "image/webp",
            },
          ],
          siteName: "MurrayGPT: Generate Bill Murray quotes.",
        }}
        twitter={{
          handle: "@echobind",
          cardType: "summary_large_image",
        }}
      />
      <Component {...pageProps} />
    </>
  );
}
